# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(345, 135)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(345, 135))
        MainWindow.setMaximumSize(QtCore.QSize(345, 135))
        MainWindow.setBaseSize(QtCore.QSize(345, 135))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(False)
        MainWindow.setWindowOpacity(0.9)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: black;\n"
"    color: whitesmoke;\n"
"}\n"
"\n"
"QPushButton, QLineEdit {\n"
"    background-color: #1c1c1c;\n"
"    color: whitesmoke;\n"
"    border: 1px solid #333333;\n"
"    border-radius: 6px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:focus, QLineEdit:focus {\n"
"    border: 1px solid whitesmoke;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #333333;\n"
"}\n"
"\n"
"QWidget:disabled {\n"
"    color: #555555;\n"
"    background-color: #121212;\n"
"    border-color: #222222;\n"
"}\n"
"\n"
"QToolTip {\n"
"    background-color: black;\n"
"    color: whitesmoke;\n"
"    border-radius: 0px;\n"
"}")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.centralwidget.setFont(font)
        self.centralwidget.setMouseTracking(False)
        self.centralwidget.setObjectName("centralwidget")
        self.INJECT = QtWidgets.QPushButton(self.centralwidget)
        self.INJECT.setGeometry(QtCore.QRect(10, 10, 321, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.INJECT.sizePolicy().hasHeightForWidth())
        self.INJECT.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.INJECT.setFont(font)
        self.INJECT.setMouseTracking(True)
        self.INJECT.setToolTipDuration(-1)
        self.INJECT.setStyleSheet("")
        self.INJECT.setObjectName("INJECT")
        self.AnimPackId = QtWidgets.QLineEdit(self.centralwidget)
        self.AnimPackId.setGeometry(QtCore.QRect(10, 50, 130, 35))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.AnimPackId.setFont(font)
        self.AnimPackId.setMouseTracking(True)
        self.AnimPackId.setToolTipDuration(-1)
        self.AnimPackId.setAutoFillBackground(False)
        self.AnimPackId.setStyleSheet("")
        self.AnimPackId.setMaxLength(10)
        self.AnimPackId.setCursorPosition(0)
        self.AnimPackId.setAlignment(QtCore.Qt.AlignCenter)
        self.AnimPackId.setClearButtonEnabled(True)
        self.AnimPackId.setProperty("minimum", 0)
        self.AnimPackId.setProperty("maximum", 0)
        self.AnimPackId.setProperty("value", 0)
        self.AnimPackId.setObjectName("AnimPackId")
        self.AnyAnimId = QtWidgets.QLineEdit(self.centralwidget)
        self.AnyAnimId.setGeometry(QtCore.QRect(150, 50, 181, 35))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.AnyAnimId.setFont(font)
        self.AnyAnimId.setMouseTracking(True)
        self.AnyAnimId.setToolTipDuration(-1)
        self.AnyAnimId.setAutoFillBackground(False)
        self.AnyAnimId.setStyleSheet("")
        self.AnyAnimId.setMaxLength(20)
        self.AnyAnimId.setFrame(True)
        self.AnyAnimId.setAlignment(QtCore.Qt.AlignCenter)
        self.AnyAnimId.setClearButtonEnabled(True)
        self.AnyAnimId.setProperty("minimum", -1000)
        self.AnyAnimId.setProperty("maximum", 1000)
        self.AnyAnimId.setProperty("value", 70)
        self.AnyAnimId.setObjectName("AnyAnimId")
        self.SetPack = QtWidgets.QPushButton(self.centralwidget)
        self.SetPack.setGeometry(QtCore.QRect(10, 90, 130, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SetPack.sizePolicy().hasHeightForWidth())
        self.SetPack.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SetPack.setFont(font)
        self.SetPack.setMouseTracking(True)
        self.SetPack.setToolTipDuration(-1)
        self.SetPack.setStyleSheet("")
        self.SetPack.setObjectName("SetPack")
        self.SetAnyAnim = QtWidgets.QPushButton(self.centralwidget)
        self.SetAnyAnim.setGeometry(QtCore.QRect(150, 90, 91, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SetAnyAnim.sizePolicy().hasHeightForWidth())
        self.SetAnyAnim.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.SetAnyAnim.setFont(font)
        self.SetAnyAnim.setMouseTracking(True)
        self.SetAnyAnim.setToolTipDuration(-1)
        self.SetAnyAnim.setStyleSheet("")
        self.SetAnyAnim.setObjectName("SetAnyAnim")
        self.Loop = QtWidgets.QCheckBox(self.centralwidget)
        self.Loop.setEnabled(True)
        self.Loop.setGeometry(QtCore.QRect(250, 90, 81, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Loop.sizePolicy().hasHeightForWidth())
        self.Loop.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Loop.setFont(font)
        self.Loop.setStyleSheet("")
        self.Loop.setObjectName("Loop")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RobloHck 3000"))
        self.INJECT.setToolTip(_translate("MainWindow", "Press it before using cheat and after joining game"))
        self.INJECT.setText(_translate("MainWindow", "INJECT"))
        self.AnimPackId.setToolTip(_translate("MainWindow", "Animation pack id"))
        self.AnimPackId.setText(_translate("MainWindow", "2623795"))
        self.AnimPackId.setPlaceholderText(_translate("MainWindow", "Animation pack id"))
        self.AnyAnimId.setToolTip(_translate("MainWindow", "Any anim id"))
        self.AnyAnimId.setText(_translate("MainWindow", "15693621070"))
        self.AnyAnimId.setPlaceholderText(_translate("MainWindow", "Any anim id"))
        self.SetPack.setToolTip(_translate("MainWindow", "Sets animation pack"))
        self.SetPack.setText(_translate("MainWindow", "Set anim pack"))
        self.SetAnyAnim.setToolTip(_translate("MainWindow", "Sets any animation"))
        self.SetAnyAnim.setText(_translate("MainWindow", "Set any\n"
"anim"))
        self.Loop.setToolTip(_translate("MainWindow", "Loop any anim"))
        self.Loop.setText(_translate("MainWindow", "Loop"))
